#include "3rdparty/robot/src/mouse.h"
#include "3rdparty/robot/src/deadbeef_rand.h"
#include "3rdparty/robot/src/keypress.h"
#include "3rdparty/robot/src/screen.h"
#include "3rdparty/robot/src/screengrab.h"
#include "3rdparty/robot/src/MMBitmap.h"
#include "3rdparty/robot/src/snprintf.h"
#include "3rdparty/robot/src/microsleep.h"
#include "3rdparty/robot/src/xdisplay.h"
#include "3rdparty/robot/src/keycode.h"

